dev: scopeのvalidation無効化 (Neovimのプラグインをscopeに指定したいため)
今後有効に戻す可能性もあるが低いかな...リリース不要だし

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -30,17 +30,17 @@ function validateType() {
 }
 
 # $1: scope
-function validateScope() {
-  case $1 in
-  linux | windows | neovim | ahk | toki | lazygit | owl | git | "") ;;
-  *)
-    echo "Invalid scope: $1"
-    echo ">> linux | windows | neovim | ahk | toki | lazygit | owl | git"
-    exit 1
-    ;;
-  esac
-}
+# function validateScope() {
+#   case $1 in
+#   linux | windows | neovim | ahk | toki | lazygit | owl | git | "") ;;
+#   *)
+#     echo "Invalid scope: $1"
+#     echo ">> linux | windows | neovim | ahk | toki | lazygit | owl | git"
+#     exit 1
+#     ;;
+#   esac
+# }
 
 validateType "${type}"
 
-tr "/" \\n <<<"${scope}" | while read -r f; do validateScope "$f"; done
+# tr "/" \\n <<<"${scope}" | while read -r f; do validateScope "$f"; done
